name: PulseSpigot Build

on: []

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Install Minecraft server to local repo
      run: |
        git submodule update --init
        ./remap.sh

    - name: Build with Maven
      run: mvn clean package --file $GITHUB_WORKSPACE/pom.xml
      
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PulseSpigot-server
        path: ${{ github.workspace }}/PulseSpigot-Server/target/PulseSpigot.jar

    - name: Upload API Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PulseSpigot-API
        path: ${{ github.workspace }}/PulseSpigot-API/target/PulseSpigot-API.jar
