name: PulseSpigot Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:  

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Install Minecraft server to local repo
        run: |
          git submodule update --init
          ./remap.sh

      - name: Build with Maven
        run: mvn clean package --file $GITHUB_WORKSPACE/pom.xml

      - name: Upload Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          release_name: Nightly Build
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/PulseSpigot-Server/target/PulseSpigot.jar
            ${{ github.workspace }}/PulseSpigot-API/target/PulseSpigot-API.jar
