name: PulseSpigot Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
          cache: gradle

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          release_name: Nightly Build
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            PulseSpigot-Server/build/libs/pulsespigot-server-1.8.8-R0.1-SNAPSHOT
